#数据库的配置信息
spring:
  datasource:
    #数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据池配置信息  # druid连接池驱动
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.100.52.189:3301/wlb_jp?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull #自己的数据库名称
    username: root_xjb
    password: rootxjb
  druid:
    initial-size: 5
    # 最小连接数
    min-idle: 5
    #最大连接数
    max-active: 1200
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 600000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 30000
    validation-query: SELECT 1 FROM DUAL
    #验证连接的有效性
    test-while-idle: true
    #获取连接时候验证，会影响性能
    test-on-borrow: false
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    use-global-data-source-stat: true
    #druid监控开关
    filter:
      config:
        enabled: true
    web-stat-filter:
      enabled: true
      url-pattern: /*
      exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
      allow: 127.0.0.1
      reset-enable: false
      login-username: admin
      login-password: admin



